name: Build and Release

on:
  push:
    tags:
      - 'v*' # v1.0, v1.1 gibi tag atıldığında çalışır
  workflow_dispatch: # Manuel olarak da tetiklenebilir

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            artifact_name: FaceBlur_Windows.exe
            asset_name: FaceBlur_Windows
          - os: macos-latest
            artifact_name: FaceBlur_macOS
            asset_name: FaceBlur_macOS
          - os: ubuntu-latest
            artifact_name: FaceBlur_Linux
            asset_name: FaceBlur_Linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Build Tools (Linux Only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk

      - name: Build with PyInstaller (Windows)
        if: runner.os == 'Windows'
        run: |
          pyinstaller --noconsole --onefile --name "Yüz Bulanıklaştırma" `
          --add-data "blaze_face_short_range.tflite;." `
          --add-data "haarcascade_frontalface_default.xml;." `
          --collect-all customtkinter `
          --icon="app_icon.ico" `
          main.py


      - name: Build with PyInstaller (macOS)
        if: runner.os == 'macOS'
        run: |
          pyinstaller --noconsole --onefile --name "Yüz_Bulanıklaştırma" \
          --add-data "blaze_face_short_range.tflite:." \
          --add-data "haarcascade_frontalface_default.xml:." \
          --collect-all customtkinter \
          main.py

      - name: Build with PyInstaller (Linux)
        if: runner.os == 'Linux'
        run: |
          pyinstaller --noconsole --onefile --name "Yüz_Bulanıklaştırma" \
          --add-data "blaze_face_short_range.tflite:." \
          --add-data "haarcascade_frontalface_default.xml:." \
          --collect-all customtkinter \
          main.py


      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: dist/FaceBlur*
